"use strict";
let car1 = 'Revo';
console.log("Is car1 == 'Revo' ? 'I predict True'");
console.log(car1 == 'Revo');
let car2 = 'V8';
console.log("Is car2 == 'V8' ? 'I predict True'");
console.log(car2 == 'V8');
let car3 = 'Mercedes';
console.log("Is car3 == 'Mercedes' ? 'I predict True'");
console.log(car3 == 'Mercedes');
let car4 = 'GWagon';
console.log("Is car4 == 'GWagon' ? 'I predict True'");
console.log(car4 == 'GWagon');
let car5 = 'Ford';
console.log("Is car5 == 'Ford' ? 'I predict True'");
console.log(car5 == 'Ford');
let car6 = 'Lamborgini';
console.log("Is car6 == 'Ferari' ? 'I predict False'");
console.log(car6 == 'Ferari');
let car7 = 'Supra';
console.log("Is car7 == 'City' ? 'I predict False'");
console.log(car7 == 'City');
let car8 = 'Bugati';
console.log("Is car8 == 'Tundra' ? 'I predict False'");
console.log(car8 == 'Tundra');
let car9 = 'Civic';
console.log("Is car9 == 'Surf' ? 'I predict False'");
console.log(car9 == 'Surf');
let car10 = 'Fortuner';
console.log("Is car10 == 'Corolla' ? 'I predict False'");
console.log(car10 == 'Corolla');
